### ISSUE TITLE
position block video

### ISSUE THREAD

**Issue by radioactive68** [paypal/accessible-html5-video-player#50]
Собственно если задать плееру позицию absolute и разместить по центру экрана то строка прогресс начинает при нажатии считать расстояние от края экрана а не от края плеера, изза этого воспроизведение видео начинается  не от туда - где указал

add test
```css
.px-video-container{
position:fixed;
left:50%;
margin-left:-320px;
}
```

correction
https://github.com/paypal/accessible-html5-video-player/blob/master/js/px-video.js#L449
```jquery
obj.pos = (e.pageX - $(this).offset().left) / this.offsetWidth;
```
